### ISSUE TITLE
Gerar variação ou especificação com termo correto

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#114]
No painel atualmente é usado o variations grids, que pode ser acessado em https://github.com/ecomplus/admin/blob/master/src/json/misc/variations_grids.json para parsear a especificação para o parâmetro específico que o Google aceita. No entanto, produto que tenha especificação Idade por exemplo, não está sendo convertida em age_group, mesmo a mudança sendo realizada no json. Possível origem do erro:

https://github.com/ecomplus/admin/blob/92bfa2749b22650ca4b342e3a4e3c7d5d6973fe1/src/assets/js/routes/resources/form/products.js#L69

**Comment by leomp12** [comment]
@matheusgnreis conversamos sobre isto no Slack e achei que tinha sido resolvido, não?
