### ISSUE TITLE
Variação com inputs editáveis

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#115]
Permitir que seja criado variação com input de texto (editável) no painel em variações.

**Comment by leomp12** [comment]
@matheusgnreis já temos como criar grades customiáveis, mas teste por favor se já é possível adicionar o campo customizável no produto pelo painel.
Se ele já fica salvo em `customizations` ou pelo menos em `grids`, com isto podemos implementar no Storefront.

**Comment by matheusgnreis** [comment]
Ok, vou testar

**Comment by matheusgnreis** [comment]
Não aparece no produto. No grid aparece o seguinte:
```
"custom_value": true
```
Se marcado.

**Comment by leomp12** [comment]
@matheusgnreis sim, está funcionando pra salvar o grid, mas claro que também precisamos associar o produto ao respectivo grid customizável, isto ainda não é possível portanto? Se for o caso é este o TODO pra depois implementar no Storefront.

**Comment by leomp12** [comment]
Não é feito nas variações especificamente, são opções de customização do produto mesmo.
