### ISSUE TITLE
Em Canais de venda > Loja > Configurações sempre retorna 404

### ISSUE THREAD

**Issue by thiagoabreudev** [ecomplus/admin#118]
Ao tentar acessar as configurações de uma loja sempre retorna 404

**Comment by leomp12** [comment]
Na verdade é possível que esses "canais de venda" sejam até deletados por agora.
As configurações do Storefront (canal de venda) acabaram por ficar fora do admin (no CMS).

**Comment by leomp12** [comment]
Issue duplicado, já resolvido.
