### ISSUE TITLE
Quando faz alteração em massa de produto não está funcionando

### ISSUE THREAD

**Issue by thiagoabreudev** [ecomplus/admin#120]
Na listagem de produtos, seleciono mais de um produto e clico no botão "Editar selecionados" e posteriormente "estoque e preços". Ao fazer isso abre a modal para atualizar os preços, porém após fazer a modificação e salvar, não está sendo salvo a alteração nos items.

**Comment by leomp12** [comment]
@matheusgnreis você chegou a fazer isto? Estava funcionando (ainda está em produção)?

**Comment by matheusgnreis** [comment]
Eu fiz teste no dev agora mesmo, inseri categorias em massa normalmente e alterei valor para promoção e entrei no produto e foi também. A questão que pode ter ocorrido no teste do @thiagoabreudev é que quando damos desconto por exemplo, ele altera dentro do produto, mas na lista em si demora um pouco pra mostrar. Mas se entrar dentro do produto a alteração é realizada. Eu de fato não sei porque demora na lista, pois eu recarrego ela na função load que havia, então deveria mostrar o novo preço.

**Comment by matheusgnreis** [comment]
Em produção está com o mesmo procedimento, mas vou olhar ela novamente, porque tem muito tempo que fiz, então pode ser se fizer muita alteração de uma vez, pode dar pau, não me lembro ao certo o que alterei, de toda forma dá para melhorar

**Comment by ThaisChaves** [comment]
Esta dando problema com a quantidade.
Testei data início e fim da promoção, preço e funcionou.

**Comment by ThaisChaves** [comment]
Problemas que encontrei no novo teste:
1- Data Início e fim esta salvando no cadastro com 1 dia antes. 
Exemplo: 
* Coloco: 01/09/2020 a 30/09/2020. 
* Salva no cadastro: 31/08/2020 a 29/09/2020.

2- Quantidade Não funciona. Coloco a quantidade e não salva no cadastro.

**Comment by matheusgnreis** [comment]
Quando foi feito a migração, dos sistemas, parece que o ID lá de quantidade saiu do local e ai não enviaria por por isso. Acabei removendo ele de fez e inserindo name pra buscar a quantidade. Antes se tivesse o id no input funcionaria apenas para produtos simples, agora funciona para variação também. Quanto a data de promoção, era por causa do -3 de timezone, retirei tbm

**Comment by leomp12** [comment]
@matheusgnreis migração dos sistemas?
