### ISSUE TITLE
Head não funciona na edição de produto

### ISSUE THREAD

**Issue by leomp12** [ecomplus/admin#122]
O head parou de funcionar na nova versão na formulário de produtos:

![Screenshot_2020-05-21 E-Com Plus Dashboard App](https://user-images.githubusercontent.com/10326572/82521736-c625f080-9afd-11ea-8cfc-40c8fa0906ec.png)

Anteriormente (a versão ainda em produção) aparecia:

![Screenshot_2020-05-21 E-Com Plus Dashboard App(1)](https://user-images.githubusercontent.com/10326572/82521732-c4f4c380-9afd-11ea-91b3-4515760b7ce5.png)

Nos outros resources também não aparecia, foi fixado no commit https://github.com/ecomplus/admin/commit/81ad23cced0225926fbba7b27615bf0860da25f3 , mas o problema segue especificamente para produtos agora.

**Comment by leomp12** [comment]
Acabei de notar o mesmo problema com clientes

**Comment by thiagoabreudev** [comment]
https://github.com/ecomplus/admin/pull/123
