### ISSUE TITLE
mudar atributo colors para color para gmc

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#141]
Problema que todas as variações criadas, irão dar problema, porque elas irão começar a renderizar apenas colors na variação. Ou seja, ou alterar aqui, ou altera no product feed, onde tiver colors, mudar para color no feed

**Comment by leomp12** [comment]
Isto não é aqui, na verdade o `colors` é uma definição da Store API, este issue seria referente ao https://github.com/ecomplus/products-feed

**Comment by matheusgnreis** [comment]
Pensei em colocar lá também, mas fiquei na dúvida mas acho q lá é melhor por causa de não alterar os produtos na e-com plus

**Comment by leomp12** [comment]
Tem que ser lá, não é uma opção haha
Mudar no admin não funciona porque isto é uma definição da API, e mexer na API é fora de cogitação só pra isto, sacou? Tava só esperando você ver mesmo pra fechar aqui.
