### ISSUE TITLE
Pesquisa de cupom na lista de pedidos do painel não está funcionando

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#152]
Na lista de pedidos ao pesquisar por qualquer cupom, retorna nenhum resultado. De acordo com pessoal observeram já tem 1 semana pelo menos

**Comment by leomp12** [comment]
A pesquisa não é pelo cupom, nunca foi, é pelo _Rótulo_ (`label`) da campanha, que não necessariamente será o nome do cupom, depende da configuração da regra de desconto.

**Comment by leomp12** [comment]
E segue funcionando normalmente, na 1011 por exemplo busque por _teste_. Confirmando feche o issue por favor @matheusgnreis

**Comment by leomp12** [comment]
Até porque a busca e o campo não são restritos a cupom de desconto, também é válido para desconto por UTM ou brinde.
