### ISSUE TITLE
Erro ao inserir GTIN nas variações

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#162]
O painel não permite inserir GTIN nas variações, informando que data.variations[0].gtin precisa ser uma string
Vide comunidade https://community.e-com.plus/t/gtin-nos-produtos-e-variacoes/437/3

**Comment by leomp12** [comment]
https://github.com/ecomplus/admin/commit/10b864f7baeaf1bd31ca16b345b90985fb27c353
