### ISSUE TITLE
Criar filtro para produtos visíveis / Disponíveis para compra no painel administrativo

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#178]
Adicionar no painel administrativo, na exibição de todos os produtos, filtro por produtos visíveis ou não visíveis na loja.
Sugestão retirada da [comunidade](https://community.e-com.plus/t/sugestao-filtro-para-produtos-visiveis-nao-visiveis-na-loja/599).

**Comment by ThaisChaves** [comment]
Incluir também filtro de "Disponível para Compra"

**Comment by leomp12** [comment]
https://github.com/ecomplus/admin/commit/5efdc597cc6e014e7938da2537e37fa70a9c1efc

**Comment by ThaisChaves** [comment]
Uhu!!! Ficou ótimo!!!! :1st_place_medal:
