### ISSUE TITLE
Edição em massa não altera a quantidade do produto.

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#190]
Selecionei alguns produtos, acionei: **Editar selecionados** > **estoque e preços**.
Coloquei quantidade 0 e também 100.
Salvei. 
No canto superior esquerdo retornou: **Edição em massa completa**, mas a quantidade dos produtos permaneceu.

Teste feito na empresa 1011 nos produtos abaixo:
![produtos](https://user-images.githubusercontent.com/60987858/90622566-a8932080-e1eb-11ea-9c39-e467516437f0.png)

Problema encontrado devido tópico da [comunidade](https://community.e-com.plus/t/sugestao-filtro-para-produtos-visiveis-nao-visiveis-na-loja/599/6).

**Comment by leomp12** [comment]
@ThaisChaves verifica por favor se este issue não é duplicado desse aqui https://github.com/ecomplus/admin/issues/120

**Comment by ThaisChaves** [comment]
Sim. É o mesmo problema. Estou fechando aqui.
