### ISSUE TITLE
nome das variações gerado errado

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#205]
Na loja custom cabos, o cliente relatou que as variações foram geradas com nome contrário. Repliquei e realmente, segue o print do lojista:
![f5241ede1c6d2120e22efcedbe9217c3bfebcd81](https://user-images.githubusercontent.com/35343551/91861425-2a029e00-ec43-11ea-86df-35a1dd439b67.png)
A variação é de 3 metros e o nome aparece de 5 metros.

No caso do meu teste:
![Captura de tela de 2020-09-01 11-07-05](https://user-images.githubusercontent.com/35343551/91861527-50c0d480-ec43-11ea-8522-c1ede0575980.png)
No caso, tem variação p10 e 3 metros, no name apareceu apenas 5 metros

**Comment by leomp12** [comment]
@matheusgnreis você testou isso em um produto novo?

**Comment by matheusgnreis** [comment]
sim, criei um produto novo

**Comment by matheusgnreis** [comment]
Deletei o que ele tinha e fiz outro

**Comment by leomp12** [comment]
Uai, mas não teve alteração nisso, está acontecendo com outras grades?

**Comment by matheusgnreis** [comment]
vou olhar aqui, pode ser que seja porque é uma grade diferente né

**Comment by leomp12** [comment]
@matheusgnreis pior que mesmo testando com estas grades na loja dele eu não vi esse mesmo erro:

![Screenshot_2020-09-01 E-Com Plus Dashboard App](https://user-images.githubusercontent.com/10326572/91884171-f5e7a700-ec5b-11ea-96bf-376e1212ffa7.png)

**Comment by leomp12** [comment]
O problema era o _+_, tava cagando um RegEx, já corrigi.
