### ISSUE TITLE
Sugestão de mostrar o numero de venda dos produtos

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#208]
Incluir na listagem de TODOS OS PRODUTOS o número de vendas dos produtos (conforme existia na Club).

Sugestão da [comunidade](https://community.e-com.plus/t/numero-de-vendas-do-produto/704).
Sugestão da [comunidade](https://community.e-com.plus/t/relatorio-mais-vendidos/766).

**Comment by leomp12** [comment]
Nao sei se colocamos isto direto na lista de produtos mesmo ou em cards SPA da home (TODO).

**Comment by ThaisChaves** [comment]
@leomp12 , tem 2 clientes na comunidade que me cobraram um retorno. Eu informei que haviam algumas prioridades, mas que tentaria agilizar para eles...

**Comment by leomp12** [comment]
Nem é questão de prioridade, o ponto é que eu queria resolver isto com uma implementação maior no admin, não só um campo a mais na lista de produtos por exemplo...
Isso faria parte do projeto da home com cards e um SPA mais complexo e bacana, sacou? Vamos começar isto na semana que vem.
