### ISSUE TITLE
Não está sendo possível salvar alterações de uma coleção

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#212]
Insere-se um novo produto e ao clicar em salvar, ele não permite informando que não existem informações a serem salvas, porém se acompanhar por exemplo a aba avançado, vemos que o novo produto foi inserido, mas não é possível salvar. Testei em categorias, marcas e grades e todos esses aceitavam modificações.

**Comment by matheusgnreis** [comment]
Após um novo teste, apenas as edições de inserir produtos que não está salvando, mas se por exemplo eu inserir um novo produto e editar o nome, ele permite eu salvar. Então são edições de adicionar apenas, que mesmo mostrando a alteração no json, ele não permite salvar

**Comment by leomp12** [comment]
@matheusgnreis você nem aprovou a PR da versão nova e já tá abrindo mais issue, credo haha

**Comment by matheusgnreis** [comment]
Reclamaram na comunidade, vi o e-mail na hora e mandei haha
