### ISSUE TITLE
Suggestion to create sales report

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#218]
Create a report showing the top selling items by sku. The user will define the period to be searched.

Sugestion of [community](https://community.e-com.plus/t/relatorio-mais-vendidos/766).

**Comment by leomp12** [comment]
@ThaisChaves poliglota :smile: 

Isto eu também planejava como um card da home em V1 (só existe no meu sonho ainda), @fabioguieiro vai nos socorrer no admin, talvez com uma mão do @thiagoabreudev se o ML tiver fim :grimacing:

**Comment by leomp12** [comment]
Esse não é duplicado desse https://github.com/ecomplus/admin/issues/208 @ThaisChaves ?

**Comment by ThaisChaves** [comment]
Opa! Poliglota graças a vc heim @leomp12 , hehe.
Realmente depois que você me explicou ficou duplicado com o 208. Vou fechar esse. Abraço!
