### ISSUE TITLE
erro nos produtos ao exportar tabela de produtos

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#221]
Ao exportar a tabela de produtos, o header varia de acordo com o primeiro produto selecionado, ou seja, se você seleciona um produto sem variação primeiro e depois os demais com variações, as informações que irão aparecer é somente o que o produto sem variação limitar. 

A título de exemplo, temos a tabela https://docs.google.com/spreadsheets/d/11exYAcH6MwqzeT3e6Cl6QwLVTeQ7fzHCIUDjeUuQaMM/edit?usp=sharing 
Isso é um grande problema, pois se o primeiro produto selecionado tiver apenas 1 variação e os demais tiverem mais de uma, se importar aquela tabela, estarei apagando demais variações do produto, só porque não saiu na tabela.

**Comment by leomp12** [comment]
Começa aqui https://github.com/ecomplus/admin/blob/master/src/controllers/resources.js#L536
