### ISSUE TITLE
Erro ao criar grade customizavel na página de produto 

### ISSUE THREAD

**Issue by vitorrgg** [ecomplus/admin#227]
Ao tentar salvar um produto após adicionar uma grade customizável é exibida a seguinte mensagem de erro: "data.customizations[0].options should be object"
  

![image](https://user-images.githubusercontent.com/35348281/94603594-d3ea4000-026c-11eb-8ecb-197ab34343ac.png)

**Comment by leomp12** [comment]
Só acontece em grades que têm opções pré-definidas..
