### ISSUE TITLE
Pedido cancelado volta status para pendente

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#230]
Ao acessar pelo admin o pedido e alterar o status financeiro para "cancelado", o sistema coloca o pedido como cancelado e algum tempo depois volta para Pendente novamente.

[Clica Aqui!](https://drive.google.com/file/d/12nJShjFr-h31bJDBzUhf2S83rms2G_kh/view) e veja o passo a passo que fiz!

**Comment by matheusgnreis** [comment]
Isso ocorre normalmente, quando o pedido acabou de ser criado. O lojistas as vezes fazendo um teste, cancela no painel rapidamente, enquanto o pedido não tem status ainda e como tudo funciona assincronamente, um pouco depois, o pedido que inicialmente estava sem status, depois foi colocado como cancelado, recebe o status de aguardando pagamento e assim, um pedido que estava cancelado, volta a ficar ativo. Algo similar ocorre no storefront, se o pedido foi colocado como cancelado, assim que foi criado, ocorre o mesmo procedimento. Apesar de isso ocorrer em raras situações com cliente em loja, somente se ele comprar e bater na cabeça que nao quer mais no segundo depois, ocorrerá apenas em testes. Mas como eu e thais recebemos alguma reclamações disso, resolvemos colocar aqui.

**Comment by leomp12** [comment]
Não deveria ocorrer mesmo, mas de fato vai ser só nesses casos quase imediatos, é um _bugzinho_ :stuck_out_tongue: 
E não seria um issue do admin, o admin não faz alteração automática, na verdade seria um issue do https://github.com/ecomplus/procedures

**Comment by ThaisChaves** [comment]
Aberto novo no local correto:
https://github.com/ecomplus/procedures/issues/8
