### ISSUE TITLE
Editar variação erro

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#250]
Produtos importados via Tiny/Bling gera o seguinte erro:

df8715e8cee5789c7b34.js:2 Uncaught TypeError: Cannot read property 'title' of undefined

elSpecs += '<h4><small class="subtitle m-0">' + Grids[gridId].title + '</small>'

Na lista mostra normal, mas na variação nao abre
![errovar](https://user-images.githubusercontent.com/35343551/97088118-1c471480-1605-11eb-9c1e-a76a1f2821c7.png)
![errovar-1](https://user-images.githubusercontent.com/35343551/97088115-12bdac80-1605-11eb-8e40-5506bd974f0f.png)

**Comment by leomp12** [comment]
@matheusgnreis não são todas as variações importadas do Tiny, veja aqui na 1011 por exemplo https://app.e-com.plus/#/resources/products/5f94f838b2161709fa43788b

Tem `title` de muita coisa, preciso que você cole o err stack todo, copia tudo que está no cosole deste erro e cola dentro de um bloco de código ([Mastering Markdown](https://guides.github.com/features/mastering-markdown/)) aqui por favor.

Além disto, pelo nome do arquivo que você colocou, você estava usando uma versão antiga, talvez em cache, não que tenha mudado algo disto, mas...

**Comment by leomp12** [comment]
Fui testar eu mesmo, na verdade o erro era por causa de uma grade `t_a_m_a_n_h_o_s` que ele tem salva lá, vou fixar uma coisa pra funcionar mesmo com isso, mas parece um teste isso aí, pode ser interessante remover e usar o `sizes` padrão (não precisa criar a grade)...
