### ISSUE TITLE
Erro de exportação listar todos ou completa

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#251]
Tanto na exportação **listar todos**, quanto na 56564681513 ele **elimina os zeros à esquerda** do sku, pode ser que ocorra com outro elemento também. Fiz um teste, um sku que é  0056564681513, saiu como: 56564681513. Logo, se a pessoa pegar a mesma tabela e importar sem fazer alteração nenhuma, vai editar os skus todos.

**Comment by leomp12** [comment]
Você testou onde? Abriu o CSV com qual programa?
Na exportação acho que não há nada que pudesse cortar zeros da string, mas a maioria dos editores de planilha entendem que é numérico e removem os zeros ã esquerda, acho que não tem muito o que fazer porque não tem como especificar a tipagem da coluna pra `String` no CSV, talvez isso seja configurável no editor.

**Comment by matheusgnreis** [comment]
No google docs

**Comment by leomp12** [comment]
Pois é, confere em um editor de texto simples (notepad) ou de código...

**Comment by matheusgnreis** [comment]
Testei no bloco de notas e estava lá
