### ISSUE TITLE
Erro Painel está salvando o GTIN como string

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#252]
Antes estava gerando como array, porém não dava para apagar, agora dá para apagar, mas está errado de acordo com a documentação

```
      "gtin": "0000980980980"
```

**Comment by leomp12** [comment]
Uai, não entendi, qual erro está dando? Está salvando como string?
É pra ser salvo como string mesmo uai, e na documentação também está string na referência, é uma string numérica...
Se tentar salvar com type incorreto a API nem aceita, tá falhando o PATCH?

**Comment by matheusgnreis** [comment]
Não, o GTIN é um array de string, não esta salvando como array, e sim como uma string
![arrayadmin](https://user-images.githubusercontent.com/35343551/97093282-e879e800-1620-11eb-957e-a70ddcbb1b02.png)

**Comment by leomp12** [comment]
Ah sim, achei que você tava falando do elemento do array...

Em sáb, 24 de out de 2020 17:48, Matheus Reis <notifications@github.com>
escreveu:

**Comment by leomp12** [comment]
@matheusgnreis você está falando de GTIN de variação só? De variação é só uma string mesmo:

![Screenshot_2020-10-25 APIs Environment · E-Com Plus Developers](https://user-images.githubusercontent.com/10326572/97099832-4849b080-166c-11eb-91fa-d0fdfeefaea5.png)

Do produto principal que é um array de strings...
Se tentar salvar com type incorreto a API nem aceita, tá falhando o PATCH? Se tiver salvando o type está certo.

**Comment by matheusgnreis** [comment]
Isso, só variação

**Comment by leomp12** [comment]
Então tá tudo certo uai, `variations[].gtin` é string mesmo.
Vou fechar o issue, se realmente tiver dando erro pra salvar ou não estiver mantendo a edição do GTIN você abre novamente por favor.
