### ISSUE TITLE
Sugestão de colocar opção para "produto Visível" em edição em massa

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#258]
Acrescentar em edição em massa a opção para **Produto visível** no produto.

Sugestão retirada da [comunicade](https://community.e-com.plus/t/atualizacao-do-painel-administrativo/958/6).

**Comment by ThaisChaves** [comment]
@leomp12 , tudo bem? 
Isso é simples pra liberar mais rápido? A voller estava querendo! Abraço!

**Comment by leomp12** [comment]
Oi @ThaisChaves , é simples, podemos tentar liberar no próximo release esta semana ainda.
