### ISSUE TITLE
Sugestão de colocar coleção no cadastro do produto

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#267]
No cadastro do produto, ter a opção para incluir a coleção (assim como existe na categoria).

Isso elimina o trabalho de sair da tela do cadastro para entrar em outra tela só para incluir o produto na coleção.

Sugestão retirada da [comunidade](https://community.e-com.plus/t/inserir-produtos-em-colecoes/1013).

**Comment by leomp12** [comment]
Vai rolar por enquanto não, este faz mais sentido https://github.com/ecomplus/admin/issues/268
