### ISSUE TITLE
Não esta salvando imagens no cadastro do produto - demorando muito

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#288]
No cadastro do produto, esta demorando demais para anexar a imagem.

Veja aqui um exemplo: https://drive.google.com/file/d/1x9UmbDzmNo-FRSuNP3hI1qM-9QraxLrV/view?usp=sharing

Após solução, retornar na [comunidade](https://community.e-com.plus/t/adicionar-foto-no-cadastro-do-produto/1121).

**Comment by leomp12** [comment]
O CDN da DO (ou AWS S3) está instável, muito lento inclusive para leitura, não somente gravação.
Entrei em contato com eles, fora isso não há muito o que fazer :disappointed: 
Vou fechar porque não é um issue nosso.
