### ISSUE TITLE
Biblioteca de imagens não carrega

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#297]
Entre em um produto e ao inserir uma nova imagem, acione a biblioteca.
Ela fica carregando e não mostra nada.
![Screenshot (74)](https://user-images.githubusercontent.com/60987858/103534792-56872a80-4e6e-11eb-8d4a-7b4ffe819186.png)

**Comment by ThaisChaves** [comment]
@leomp12 : Só vai mostrar novas? Não ta mostrando na biblioteca as imagens antigas não... Só as que coloquei hoje...

**Comment by leomp12** [comment]
Só as recentes porque naquela do CDN refatorei tudo, inclusive o datacenter do block storage, aí a API só retorna os que estão nos buckets novos.
