### ISSUE TITLE
Criar contador de caracteres no título e descrição do produto.

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#311]
Criar um contador de caracteres no título e na descrição dos produtos.

Veja sugestão retirada da [comunidade](https://community.e-com.plus/t/sugestao-contador-de-caracter-nas-tags/1297/2),

Mas acho que não deveríamos limitar (conforme o exemplo que ele colocou do mercado livre), mas ter o contador é uma informação boa para o logista.

**Comment by leomp12** [comment]
> Mas acho que não deveríamos limitar

Na verdade já é limitado @ThaisChaves , só que o máximo de caracteres é grande e talvez por isso não tão perceptível...
