### ISSUE TITLE
Slug de produtos estão sendo criados sem separador

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#312]
Ao criar um novo produto, anteriormente vinha separados por hífen, agora eles aparecem com todos os nomes juntos, precisando realizar edição manual para separá-los

**Comment by ThaisChaves** [comment]
Somente para lembrar: Após correção, avisar [aqui na comunidade](https://community.e-com.plus/t/url-amigavel-sem-identacao/1324/2).
