### ISSUE TITLE
Problema com saldo no produto KIT

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#333]
Quando compro mais de um KIT em um mesmo pedido, esta baixando nos produtos que compõem o KIT somente 1 KIT:

1- No meu exemplo, o KIt esta cadastrado composto por 2 produtos e cada um tinha o saldo de 10.
2- Vendi vários KITs e o saldo dos itens que compõem  foi para 8. 
3- Consegui vender mais produtos do que tinham para compor o KIT.

![Screenshot - 2021-02-28T120032 680](https://user-images.githubusercontent.com/60987858/109422998-9e34b900-79bc-11eb-9d1b-f8a9164197d5.png)
![Screenshot - 2021-02-28T120014 067](https://user-images.githubusercontent.com/60987858/109422995-9aa13200-79bc-11eb-98e7-bdc409a3938f.png)

Vendi 16 kits:
![Screenshot - 2021-02-28T120157 339](https://user-images.githubusercontent.com/60987858/109423055-d936ec80-79bc-11eb-8e46-30a6091724c9.png)

**Comment by leomp12** [comment]
Não tenho certeza se entendi isso aqui @ThaisChaves ...

Você fez esses pedidos no painel? Os kits não serão decompostos no painel então de fato os itens que compõe o kit não serão alterados, pelo menos enquanto esse controle de estoque com kits só vai funcionar corretamente com pedidos feitos no checkout do Storefront, em pedidos do painel os produtos que compõe o kit deverão ser adicionados um a um em vez do kit em si.

Se você está falando de pedidos feitos na loja mesmo, esses prints aí não são conclusivos pra erro, no mínimo teria que ver no JSON do produto o histórico de alterações de estoque, nesse caso mesmo se realmente identificar um problema também não seria um issue do admin.
