### ISSUE TITLE
Inserir opção de sem status para pagamento

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#339]

**Comment by leomp12** [comment]
Qual a intenção disso?

**Comment by matheusgnreis** [comment]
Filtrar pedidos que não completam pagamento (deu erro) e assim tentar refazer compra, seja manual ou outra forma

**Comment by leomp12** [comment]
Mas isso só seria útil pra pedidos recentes, não?

**Comment by matheusgnreis** [comment]
Sim, mas quem tem fluxo grande de pedido, acaba deixando perdido na lista e assim pode filtrar melhor
