### ISSUE TITLE
Erro ao adicionar nova variação em produto existente

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#360]
Antes:
![Screenshot (98)](https://user-images.githubusercontent.com/35343551/114747215-fb938800-9d26-11eb-97f0-681c1198ee62.png)
Depois:
![Screenshot (99)](https://user-images.githubusercontent.com/35343551/114747235-ffbfa580-9d26-11eb-891e-757d496b9698.png)

Quando insere nova variação, elas se recombinam e selecionam todas opções possíveis, ao invés de recombinar e deixar apenas as opções já existentes no produto. Isso acaba por gerar uma grande perda de tempo, pois tem que retirar seleção das que não vão precisar, toda vez que adiciona uma nova opção

**Comment by matheusgnreis** [comment]
Bom dia, inclusive estão querendo pagar para resolver o problema das recombinações automaticas:

**Matheus, poderia nos detalhar melhor se é viável e qual valor para desativar essa recombinação automática das variações em grade na raiz do sistema mesmo?**

**Comment by leomp12** [comment]
Viável com certeza é, problema é só que eu tô mais agarrado, se você não conseguir pegar agora eu vejo na semana que vem.

**Comment by matheusgnreis** [comment]
Estava até começando a entender o código semana passada, porém tive que levar meu pc pra arrumar, chegou as peças da dobradiça, só pego ele terça, até lá vou ver se consigo aqui nos computadores de casa.

**Comment by matheusgnreis** [comment]
Eu olhando aqui, até propus uma solução, porém vi que o buraco é mais embaixo. Quando é inserido uma nova variação, o sistema refaz as variações e além disso mistura as informações exemplo: antes a variação Dark Blue não tinha nenhuma informação interna, conforme podemos ver:
![Screenshot - 2021-05-12T154335 241](https://user-images.githubusercontent.com/35343551/118029030-1f53e900-b33a-11eb-87cb-1141496fd868.png)


Depois de inserir uma variação, ela passa a ter um sku e quantidade de outro produto:

![Screenshot - 2021-05-12T154643 487](https://user-images.githubusercontent.com/35343551/118029010-19f69e80-b33a-11eb-867a-2a0d9b4e7758.png)

Sendo que esse sku e quantidade originalmente são da variação: Hardbox / Apple / iPhone 11 Pro / Black.
 Que passou a ter o sku: 298234 e a quantidade 12:

![Screenshot - 2021-05-12T160224 376](https://user-images.githubusercontent.com/35343551/118030279-760df280-b33b-11eb-979a-5be45ea9877b.png)

A imagem abaixo é o valor original de Hardbox / Apple / iPhone 11 Pro / Black, antes de qualquer alteração:
![Screenshot - 2021-05-12T155403 373](https://user-images.githubusercontent.com/35343551/118029194-50341e00-b33a-11eb-80e4-3532173ab988.png)

Então a solução nao é só desmarcar quando insere uma nova variação ou move alguma variação de lugar. Ela ao fazer um desses, mistura as informações.

**Comment by leomp12** [comment]
Vai serguir acontecendo isso quando uma nova grade é adicionada (todas as combinações são alteradas), mas não vai acontecer mais quando novas opcões são adicionadas mantendo as mesmas grades.
Também fixei uma ocasião em que o objeto da variação poderia ser invertido nessa adição de opção da grade quando alguma combinação já estava inativa, talvez seja o caso que você viu.
