### ISSUE TITLE
Erro: Não renderiza todos os itens do kit

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#362]

**Comment by leomp12** [comment]
Tem pelo menos um exemplo @matheusgnreis ?

**Comment by matheusgnreis** [comment]
Já resolvi, só colocar aqui a PR

**Comment by matheusgnreis** [comment]
Pelo que li por padrão o ES retorna 10 itens e ai precisava setar um size referente a busca que to fazendo. Coloquei o size com base na quantidade dos IDs do Kit e deu certo
