### ISSUE TITLE
Erro ao colocar observação no cadastro de cliente 

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#368]
Entro na tela do cadastro de cliente e preenche qualquer texto no campo "Informação Complementar".

Ao clicar para salvar, mostra  a msg de erro: 'staff_notes deve ser string'

Escrevi apenas a palavra teste como pode ser visto no print abaixo:
![Screenshot - 2021-05-02T102734 391](https://user-images.githubusercontent.com/60987858/116814819-04f75f80-ab31-11eb-9641-c7cabf339643.png)

O erro ocorreu na loja Lov e fiz teste também na 1011 e também ocorreu.
[Retirado do tópico da comunidade](https://community.e-com.plus/t/observacao-no-cadastro-do-cliente/1867).
'

**Comment by leomp12** [comment]
@matheusgnreis tinha um trecho tratando manualmente do `staff_notes` (e parseando para objeto), como é só um campo como qualquer outro não precisava de um handler adicional, estou só removendo por enquanto e te mencionando caso lembre do motivo de ter colocado...

**Comment by matheusgnreis** [comment]
Ou, acho que o problema era que não permitia apagar

**Comment by leomp12** [comment]
Hmm testei removendo lá e foi também, se pá faz uns testes aí
