### ISSUE TITLE
UTM criado externamente ao app de descontos nao aparece na lista de pedidos

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#379]
Na lista de pedidos aparecem apenas UTM com descontos, no caso UTM de facebook ads, Google ads, ou mesmo de influencers para traquear os pedidos que entram, não aparecem na lista de pedidos. Impossibilitando ter esse tipo de acompanhamento

**Comment by leomp12** [comment]
Na verdade não aparece UTM nenhum, o que aparece são labels de campanhas de desconto (salva no app ou não) que eventualmente correspondem ao nome da campanha UTM.

**Comment by leomp12** [comment]
Não necessariamente ao app de desconto, só aparece se tiver um desconto extra no pedido e um label pra esse desconto.
Pra botar UTM na lista teria que adicionar outra coluna porque é outro campo, problema é que a lista já está bem ocupada e cada vez menos responsiva porque tem colunas demais, talvez seja o caso de criar um relatório separado sim.
