### ISSUE TITLE
Não salva especificação no produto se houver caractere especial

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/admin#383]
No cadastro da especificação, se usar caractere especial, não esta salvando.

Aparece bem rápido essa msg na tela.
![WhatsApp Image 2021-05-18 at 21 23 51](https://user-images.githubusercontent.com/60987858/119167120-d97fda80-ba35-11eb-8c65-31332f17d20f.jpeg)

Os caracteres que o logista usa por exemplo são: º ≤ ± Ω

Tópico retirado da [comunidade](https://community.e-com.plus/t/erro-adicao-de-especificacao/1971/4).

**Comment by leomp12** [comment]
@ThaisChaves sempre que possível cole no issue os dados da request feita na API (URL, método e corpo) por favor.

> Você vai conseguir isso no network (ou rede) do console do seu navegador, nas requisições XHR.

> Não cole cabeçalhos de autenticação 😬  (não precisa de cabeçalho nenhum).

**Comment by leomp12** [comment]
Na verdade dá pra adicionar esses caracteres (testei com todos) tanto no título quanto no valor da spec sem problema nenhum, no caso o impeditivo era o tamanho do título da grade de especificação (_Faixa de medição de temperatura_).
