### ISSUE TITLE
Atrito de ux na configuração de domínio no dashboard

### ISSUE THREAD

**Issue by vitorrgg** [ecomplus/admin#416]
![image](https://user-images.githubusercontent.com/35348281/126535488-cde70528-6176-499b-b451-f3346aa7d046.png

Ideias para melhora:

- Retirar essa configuração dali, deixando apenas na página de configuração
- Permanecer com a configuração, inserindo um tooltip informando para só alterar após o direcionamento do domínio. 

A opção de editar domínio no dashboard facilita setup da loja por nós, mas alguns usuários fazem a edição acreditando que irá mudar o subdomínio temporário, outros menos informados fazem tentando colocar o domínio próprio. 

Esses usuários se deparam com os óbvios erros ao clicar nos botões logo abaixo "EDITAR FRENTE DE LOJA" ou "IR PARA LOJA" indo para um subdomínio inexistente no Netlify ou para seu domínio próprio sem ter o DNS devidamente configurado. 

Pensam ser algum erro nosso, o que desgasta a experiência do usuário na plataforma logo no início, em um momento que estariam testando o CMS, ou como ficaram os produtos que acabou de cadastrar. 

Eu pretendo regravar o vídeo inicial de primeiros passos, pois a página de "Configurações" foi bem alterada desde então, caso não alteremos essa parte vou ressaltar que ali não se muda o domínio temporário e muito menos faz o direcionamento do domínio próprio. 

Não são todos usuários que veem o vídeo, dos que veem nem todos absorvem o conteúdo dito, então com certeza não resolve. Idealmente também gravaria esse vídeo após alguma alteração nesse ponto, para que no vídeo não esteja diferente do que o usuário vê na tela.

**Comment by leomp12** [comment]
Movido para o repositório correto em https://github.com/ecomplus/admin-home/issues/20
