### ISSUE TITLE
Erro ao carregar mais produtos da lista

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#417]
Pelo meu teste, foram apenas com produtos importados de uma única loja, barradoce (3967) que foram importadas via Bling.
type: "search_phase_execution_exception" status: 500
![status_500_search](https://user-images.githubusercontent.com/35343551/126873979-c25e1c97-6f63-485a-b221-ed553be61570.PNG)
Carregando até 900 vai normal, problema é tentar carregar para abrir mais de 900, dá esse erro

**Comment by leomp12** [comment]
Tá funcionando lá, também não era um issue do admin na verdade..
