### ISSUE TITLE
Exportação Listar Todos: Question

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#421]
Atualmente, para exportador todos os produtos do painel, se a loja tiver mais de 1000 produtos, demora pelo menos 1 hora com a aba aberta na página. Uma loja com 3000 produtos me pediu pra exportar pra eles porque trabalharam muito com edição via planilha e demorou 4 horas rodando no meu pc alternando tabs. Talvez seja interessante pensar em uma forma de exportar sem demorar tanto.

**Comment by leomp12** [comment]
Ajudaria bater a Store API seu autenticação pra um rate limit menor e menos delay entre as requests.
Fora isso, é melhor paginar né? Ou deixar como tá pra exportar tudo de uma vez?

**Comment by matheusgnreis** [comment]
Eu estava pensando naquela outra forma de listar todos, mas com os fields pré-setados com pelo menos os fields que têm no painel. 
Acho que paginação fica meio ruim, pelo menos ninguem gosta na club disso e já perguntaram se na plus tinha, falei que não mas dependendo da quantidade de dados demora um cado, melhor deixar exportar o que quer, porque as vezes filtra uma categoria e busca por ela...
Talvez com rate limit menor já ajude bastante
