### ISSUE TITLE
Control + Click não funciona em aplicativos

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#433]
Não sei se alguem mais teve esse problema, mas a funcionalidade abrir nova aba para aplicativos via control + click não funciona. Ele gera a aba, mas fica em branco, precisando clicar em outra rota e depois voltar em aplicativos para funcionar.

**Comment by leomp12** [comment]
É totalmente diferente na verdade, o SPA do admin marketplace usa um router diferente e por isso os cliques e rotas não são tratados da mesma forma, pelo mesmo motivo é inviável fixar isso por enquanto, para mais de uma aba com aplicativos é necessário começar abrindo a view padrão do marketplace.
