### ISSUE TITLE
Shipping_lines[0].app propriedade id é requerida

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#442]
Ao criar um pedido, se a loja for tentar configurar informações relacionadas ao frete, como prazo de entrega, prazo de envio, transportadora e afins, não permite que crie até que seja inserido o app._id.

No caso, pensei ou colocamos o campo lá:
![download](https://user-images.githubusercontent.com/35343551/132343142-ed4b1e30-46bc-4a15-be60-dccd1f9312d8.png)
Ou geramos um app id

**Comment by leomp12** [comment]
A propriedade `id` ou `app_id`?

**Comment by matheusgnreis** [comment]
app._id
