### ISSUE TITLE
Lista de itens do pedido mostrando com quantidade e item errado

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/admin#490]
Já tentei debuggar, a informação da API está correta, não atoa a fatura que tinha feito sai com a quantidade e itens corretos sendo mostrados, mas na listagem sai errado, levando a crer o erro na função que insere os dados nos inputs. 

![image](https://user-images.githubusercontent.com/35343551/146234311-f63f5eb0-bd6e-40d0-ba95-fd432471b293.png)

O produto número 3 da lista está com mesma quantidade, preço e nome do item 6, se olhar as imagens estão diferentes, pois a imagem está correta. No 3 deveria aparecer quantidade 2, nome Tecido Nacional Coleção Love Cats Meow e preço 8,45.

**Comment by leomp12** [comment]
Deixa pelo menos uma loja e pedido de exemplo, sempre

**Comment by matheusgnreis** [comment]
coisasdateca (1125) e 61a0a8e10c7c7272259dd2f0

**Comment by leomp12** [comment]
Os items estão com IDs (`items[]._id` tem que ser único no pedido) repetidos, e por óbvio não poderia, o erro não é rendedizando a lista, o erro foi quando o pedido foi gerado dessa forma.
Como esse pedido foi criado? Foi alterado depois?

**Comment by matheusgnreis** [comment]
Criado pelo cliente direto no site. No storefront está ok. Essa renderização no painel que está errada

**Comment by matheusgnreis** [comment]
Segundo a resposta, não houve edição do pedido, descobriu somente depois que deveria enviar mais uma unidade, pois estava errado no pedido pelo painel

**Comment by leomp12** [comment]
> Essa renderização no painel que está errada

Mas aconteceu isso por causa do ID repetido, dá pra prevenir realmente mas é tapar o Sol com peneira, repetir o ID vai gerar diversos outros problemas inclusive a nível de API.
O ideal é verificar nos logs se realmente não teve alteração no pedido, mas se não houve o problema é do checkout https://github.com/ecomplus/modules-api/blob/master/routes/%23checkout.js
