### ISSUE TITLE
Erro de tipo ao inserir e salvar inscrição estadual (Cliente)

### ISSUE THREAD

**Issue by silveirajs** [ecomplus/admin#522]
Describe the bug:
Quando preenchemos o campo de Inscrição Estadual. O erro acontece ao SALVAR, aparecendo a mensagem

To Reproduce - Steps to reproduce the behavior:
Pedidos > Clientes;
Ao selecionar um cliente existente ou criar um novo cliente;
Preencher inscrição estadual no cliente Jurídico e depois SALVAR

Expected behavior:
Ao inserir a inscrição estadual e salvar, que seja finalizado corretamente e que o cadastro seja atualizado com as novas informações

![1](https://user-images.githubusercontent.com/90005059/155323046-3d18991c-8a84-48fc-9c21-579ac598593f.png)

**Comment by leomp12** [comment]
Opa, Caio na verdade isso não acontece no nosso admin, acho que é um bug do fork da Confere apenas.
Na verdade até o form é exibido diferente nesse ponto:

![Screenshot 2022-02-23 at 20-28-13 E-Com Plus Dashboard App](https://user-images.githubusercontent.com/10326572/155426881-46c47938-6554-4a16-a0ad-b289d0726712.png)

E tá salvando normal, tanto como _Municipal_ quando _Estadual_.
