### ISSUE TITLE
[RFC] Assinaturas

### ISSUE THREAD

**Issue by leomp12** [ecomplus/admin#536]
Improves para pagamentos recorrentes:
- [ ] Destaque na lista;
- [ ] Linkar pedidos consequentes da assinatura (períodos) na edição do pedido orignal, e vice-versa;

> Mais ? 🤔

**Comment by leomp12** [comment]
@matheusgnreis @sameoldcarlos

**Comment by matheusgnreis** [comment]
Caramba bicho, eu criar o RFC disso.

Estava pensando em uma segunda lista, só com pedidos recorrentes (pai)
Nessa lista, tendo como propriedade ai pra busca: Nome/email do cliente, total, periodicidade, (ideal se tivesse algo mostrando se ela está ativa ou não, acredito que do nosso lado não tem), quantos já foram pagos e forma de pagamento.

Clicando nele, abriria o pedido com uma seção mostrando os pedidos da assinatura com seus respectivos pedidos e afins.

Acho que dar um destaque na lista atual de pedidos, não iria dar uma informação sucinta para ver dados básicos de assinatura.

**Comment by leomp12** [comment]
Por _destaque na lista_ eu tô pensando em uma solução mais rápida na verdade, o que você sugeriu aí parece o ideal mas talvez demore (sem virar uma gambiarra muito grande).
Acho que o mais importante (o primeiro TODO) é _linkar pedidos consequentes da assinatura (períodos) na edição do pedido orignal, e vice-versa_, com isso já fica funcional pelo menos, não?

**Comment by matheusgnreis** [comment]
https://github.com/ecomplus/admin/pull/577
