### ISSUE TITLE
[RFC] Pontos de fidelidade

### ISSUE THREAD

**Issue by leomp12** [ecomplus/admin#537]
Improves para programas de fidelidade:
- [ ] Mostrar na lista de clients (?) 🤔 
- [ ] Relatório de clientes com pontos disponíveis (ordenados), talvez só uma lista de e-mail/nome;

**Comment by matheusgnreis** [comment]
Bom, pensei em criar uma seção customers, que vai poder visualizar todos, criar customers e vir ai alguns relatórios, exemplo:
![image](https://user-images.githubusercontent.com/35343551/177215049-5383583d-de97-4d5f-b809-4d8b722ac036.png)

**Comment by matheusgnreis** [comment]
O que acha @leomp12

**Comment by matheusgnreis** [comment]
https://github.com/ecomplus/admin/pull/630
