### ISSUE TITLE
[RFC] Admin V2 UI

### ISSUE THREAD

**Issue by leomp12** [ecomplus/admin#60]
Para a próxima major do Admin estou pensando em usar **[Ant Design Vue](https://www.antdv.com/docs/vue/introduce/)** além do [`@ecomplus/storefront-twbs`](https://github.com/ecomclub/storefront-twbs).

Continuaríamos carregando o CSS do Bootstrap e [alguns componentes do BootstrapVue](https://github.com/ecomclub/storefront-twbs/blob/master/src/index.js) principalmente para preview de componentes da loja (eg.: preview de produto usando o [`EcProduct`](https://github.com/ecomclub/widget-product)).

Mas pensei em adicionar o Ant Design como uma solução mais plug and play para o painel administrativo especificamente, tem muitos componentes prontos e aparentemente voltados para dashboards mesmo

**Não penso em utilizá-lo no storefront** para evitar bundle desnecessário (penso em carregar a lib completa no admin) e neste caso considero o Bootstrap uma solução mais comum (fácil para agências), reutilizável  e suficiente.

Portanto utilizando o Ant Design no admin teríamos um pouco menos de compatibilidade entre componentes do admin para a loja, considero um problema, mas não tão grande porque não vejo muita utilização de componentes do admin na loja, apenas o contrário me parece mais usual.

Em contrapartida acredito que usando uma lib completa em Vue no admin ajudaria bastante na nossa produtividade, considerando que o admin é um app bastante complexo.

O que vocês acham? :thinking: 
Também podemos discutir outra opção de lib em vez do Ant Design (ElementUI talvez). :+1:

**Comment by leomp12** [comment]
@thiagoabreudev não tenho como te assinar no issue mas estou te marcando aqui porque isto influencia diretamente no [ecomplus/admin-marketplace](https://github.com/ecomclub/admin-marketplace), certo?
Na verdade adiantei este RFC justamente por causa disto mesmo.

**Comment by leomp12** [comment]
> A título de curiosidade/exemplo, existe também o [Ant Design Pro](https://preview.pro.ant.design/)  :boom: , a implementação dos componentes do Ant Design em um dashboard completo (chama PRO mas também é open source), em React mas são os mesmos componentes da versão Vue

**Comment by talissonf** [comment]
Pode ser uma boa @leomp12! os components dele lembram um pouco o EllementUI. Mas eu não entendi uma coisa, o admin também vai poder customizado pelo lojista igual ao storefront?

**Comment by talissonf** [comment]
@leomp12 você pensou em ir implementando ele no admin-marketplace já?

**Comment by leomp12** [comment]
@talissonf customizado pelo lojista igual ao storefront não, pretendo só deixar ele escolher cards na home, mas mudar tema não.

Lembra um pouco o ElementUI mas ele tem mais componentes eu acho, mais funções.

Acredito que já seria útil no marketplace principalmente quando for fazer os formulários de edição dos apps.

**Comment by leomp12** [comment]
@talissonf @thiagoabreudev na verdade é uma sugestão apenas, estou adiantando esta discussão justamente pra ouvir de vocês se consideram interessante usar isto no admin marketplace.

Portanto, vocês acham que usá-lo facilitaria desing decisions e UX (principalmente em formulários) no admin marketplace? Ou acham que não faz diferença e podemos continuar (pelo menos por enquanto) com Bootstrap apenas?

**Comment by leomp12** [comment]
Quando eu falo de facilutar os formulários me refiro à utilizar os inputs mais complexos que já vêm na lib, tipo este [transfer](https://www.antdv.com/components/transfer/) ou [auto complete](https://www.antdv.com/components/auto-complete/), que não vêm no Bootstrap Vue...

**Comment by talissonf** [comment]
@leomp12 Acho que pra gente tanto faz, até porque não estamos seguindo nenhum guia de estilo pré-definido. Mas acredito que usando no inicio do desenvolvimento possa nos poupar retrabalho futuramente.

**Comment by leomp12** [comment]
Então, mas a ideia é deixar desing decisions mais explícitas, seguir um desing system sempre que possível pra criar padrões.

Além disto, no admin marketplace não chegaram ainda no ponto de criar formulários para edição de cada app específico, a intenção é ter uma UX mais bacana e pra isto vão ser necessários componentes mais complexos, inputs básicos não vão resolver, assim como no painel atualmente eu utilizo plugins como `select2` e `typeahead` em formulários de produtos, pedidos e etc.

Neste sentido temos 3 opções:
1. Fazer todos os componentes "from scratch", obviamente o mais trabalhoso;
2. Reutilizar componentes de terceiros mas apenas com Bootstrap, adaptações de desing serão necessárias para manter todos em um padrão;
3. Utilizar outra lib de UI que já venha com estes componentes out of the box, já seguindo um padrão de design (é o caso do Antv e ElementUI);

Entendeu meu ponto?
Só pra listar os apps realmente eu acredito que não faça muita diferença, a questão é quando precisarmos de views com UX mais complexas.

**Comment by thiagoabreudev** [comment]
Eu não conhecia o Ant D, achei bem interessante e completo. 

Acredito que a solução de melhor custo benefício seria a 3 - "Utilizar outra lib de UI", essas libs costumam ser bem completas pros cenários comuns. 

A opção de fazer os componentes do zero com o scratch é o melhor dos mundos, mas não sei se seria o melhor para o momento. Acredito que precisaríamos de um cara muito bom de designer pra fazer os componentes com uma identidade legal, e gastaríamos mais tempo pra poder dar vida ao componente.

**Comment by leomp12** [comment]
Na verdade, neste momento eu estava considerando as opções 2 e 3 apenas...
Esta discussão seria pra mais pra frente (pra v2 do admin mesmo), mas imaginei que talvez já ajudasse no admin marketplace.

Mas acho que ainda não chegamos exatamente em um veredicto, vocês acham que ajudaria usar o Antdv ou Element UI?
Se sim, qual deles (ou outro)?

É perfeitamente possível importar no admin marketplace um componente auto complete (por exemplo) de algum terceiro, e adaptar os estilos para acompanhar o resto do Bootstrap (e posteriormente vamos importar um tema da E-Com Plus do Bootstrap), mas seria um pouco mais trabalhoso, o ponto é, este trabalho vale a pena considerando que vamos aumentar o bundle e diminuir compatibilidade?

**Comment by leomp12** [comment]
É um peso entre produtividade/reusabilidade&perfomance, sacaram?
Então eu quero ouvir de vocês se acham se vale a pena ou não, considerando que vamos precisar de views com componentes mais complexos, formulários mais dinâmicos...

**Comment by thiagoabreudev** [comment]
Eu acho que vale a pena usar, e voto no AntD, principalmente na parte que estou mexendo e que ainda é muito fácil de trocar os componentes que fiz para os da ui!

Porém ainda tenho uma visão micro apenas de onde estou mexendo. Gostaria de saber de vocês se o impacto dessa mudança geraria muitos conflitos ao ser integrada. Não tenho a dimensão disso.

**Comment by leomp12** [comment]
Vai gerar conflitos de design até eu conseguir implementar a V2 do admin...

Além disto, usando qualquer lib a mais os componentes que fizermos para o admin não serão compatíveis com a loja (mas da loja serão compatíveis no admin).

E por último, a princípio teríamos uma "mistureba".
Só pensar o seguinte, já existe um componente usado no storefront para busca de produtos com auto complete, certo?
Naturalmente o correto é reutilizá-lo até porque não é um source tão trivial assim.
Este cara tem seus própios estilos mas a base é o Bootstrap, adicionando uma lib teríamos algumas coisas baseadas em Bootstrap e outras baseadas em outro framework.
Certamente eu vou tentar aproximar os estilos com temas pros dois frameworks, mas talvez não fique tão bom quanto...

**Comment by leomp12** [comment]
Não é meu cenário preferido (por isto não fiz isto no storefront), mas acredito que para trabalharmos em equipe precisamos de algo mais próximo de um desing system pra ganhar produtividade e manter padrões.

Além disto, no caso do painel, não acho que valeria a pena reinventar a roda para cada input picker que não está disponível no Bootstrap Vue.

**Comment by leomp12** [comment]
Meu sonho de consumo era o [Polaris](https://polaris.shopify.com/), mas o Shopify é egoísta haha

**Comment by thiagoabreudev** [comment]
Bom, com base nos últimos post do @leomp12 eu acho que vale a pena usar uma UI e que este é um bom momento. O que acha @talissonf ?

**Comment by talissonf** [comment]
Podemos tentar o Ant D, o que acham? 🙃

**Comment by leomp12** [comment]
Ok, então comecem a usá-lo no `admin-marketplace` e me dêem feedbacks por favor, vou dar mais uma pesquisada nisto por estes dias, a propósito este repositório é interessante:
https://github.com/alexpate/awesome-design-systems

**Comment by leomp12** [comment]
### Convenção: Views

Pela experiência até então com o [`admin-marketplace`](https://github.com/ecomclub/admin-marketplace) acho que **apenas definir componentes não vai ser o suficiente**. Continuamos perdendo mais tempo do que eu gostaria com decisões de design, ainda assim o resultado não me parece muito satisfatório, acredito que as views poderiam ser mais bonitas e funcionais.

Isto dito, proponho sempre tomar como base as views do [Ant Design Vue Pro](https://preview.pro.loacg.com/).
> Sim, está em chinês, eu testei uma por uma pela sidebar pra descobrir do que se trata :sweat_smile:.

A priori, **toda view deverá ser igual (ou quase) a alguma view do _Ant Design Pro_**, incluindo o source code (começar com um CTRL+C CTRL+V).
Repo/docs: https://github.com/sendya/ant-design-pro-vue

O que acham @talissonf @thiagoabreudev ? Isto já valeria para as views atuais do marketplace...

**Comment by leomp12** [comment]
@matheusgnreis você que é o cara do admin, se puder registrar sua opinião aqui também por favor..

**Comment by talissonf** [comment]
Uai Leo por mim pode ser, talvez ajude a padronizar as views e também acelere um pouco o desenvolvimento.

**Comment by matheusgnreis** [comment]
Acredito que dessa forma ficará mais fácil de trabalhar uma vez que já existem padrões, logo manterá sempre uma estrutura permitindo manter o foco em fazer código e não em design.

**Comment by thiagoabreudev** [comment]
Mas neste caso é pra trocar todas as views atuais que já estão implementadas? @leomp12

**Comment by leomp12** [comment]
@thiagoabreudev acredito que sim, mas pode ser secundário, quer abrir um issue lá a respeito inslucive pra definifirmos quais views no Ant Pro seriam usadas como base?

**Comment by thiagoabreudev** [comment]
Criei a issue [issues/14](https://github.com/ecomclub/admin-marketplace/issues/14)

**Comment by leomp12** [comment]
Vai ficar Bootstrap mesmo por um bom tempo :neutral_face:
