### ISSUE TITLE
SKU permanece o mesmo ao duplicar produto

### ISSUE THREAD

**Issue by eduvlemes** [ecomplus/admin#79]
Ao clicar em duplicar no cadastro do produto, é gerada uma página nova, sem nenhum aviso de que a operação foi feita corretamente e o SKU é salvo igual ao produto original, coisa que gera problema com algumas integrações que usam o SKU como chave principal do produto.

Sei que tem a opção do lojista apertar lá em "aleatório", mas se possível, adicionar uma validação no campo de SKU para evitar valor duplicado.

**Comment by leomp12** [comment]
@igorsfreitas mais um :stuck_out_tongue: 
Consegue trabalhar neste issue e o https://github.com/ecomclub/ecomplus-admin/issues/80 em paralelo ao que combinamos?
