### ISSUE TITLE
Configurar e adicionar webpack e babel ao projeto

### ISSUE THREAD

**Issue by thiagoabreudev** [ecomplus/admin#97]

**Comment by leomp12** [comment]
No Webpack, que me lembro de cara, precisaremos dos seguintes plugins/loaders:

- `style-loader`
- `mini-css-extract-plugin`
- `html-webpack-plugin`
- `postcss-loader`
- `sass-loader`
- `vue-loader`
- `workbox-webpack-plugin`
- `webpack-pwa-manifest`
- `terser-plugin`

**Comment by leomp12** [comment]
https://github.com/ecomplus/admin/commit/4c71583314fe4ef2997d6d73647ccae821dfa891
