### ISSUE TITLE
Refatorar roteador

### ISSUE THREAD

**Issue by thiagoabreudev** [ecomplus/admin#98]

**Comment by leomp12** [comment]
Refatorar o [router no main](https://github.com/ecomplus/admin/blob/master/src/assets/js/script/main.js#L1036) para:

- [ ] Passar a usar dynamic import (Webpack);
- [ ] Globais setadas no router deverão se tornar módulos ou passadas como parâmetros nas funções de rotas;
- [ ] As rotas (JS) deverão importar o HTML respectivo (que antes era feito [com `$.ajax`](https://github.com/ecomplus/admin/blob/master/src/assets/js/script/main.js#L1065))

**Comment by leomp12** [comment]
Tá funcionando já com Webpack, Babel e afins, router refatorado mas não 100%, de qualquer forma fechando por enquanto :stuck_out_tongue:
